version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    # Disable version updates for npm dependencies (only security updates)
    open-pull-requests-limit: 0

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    # Disable version updates for GitHub action dependencies (only security updates)
    open-pull-requests-limit: 0
